apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: moon
  namespace: argocd

spec:

  project: default

  sources:

  - repoURL: https://charts.aerokube.ru
    chart: moon2
    targetRevision: 2.8.1
    helm:
      valueFiles:
      - $values/manifests/moon-values.yaml


  - repoURL: https://github.com/sashazorin1900-maker/moon-argocd.git
    targetRevision: main
    ref: values


  destination:
    server: https://kubernetes.default.svc
    namespace: moon


  syncPolicy:
    automated:
      prune: true
      selfHeal: true
